"""add photo and comment to matches

Revision ID: 3b7e1c4a92d5
Revises: 80cb646c05dc
Create Date: 2026-08-17 21:40:00.000000

Written by hand rather than autogenerated. Autogenerate compares the models
against whichever database it is pointed at, and running it on the SQLite test
database would also emit a diff for the Postgres-only pieces of the initial
schema (the native enums, the timezone-aware timestamps). Two columns do not
justify cleaning that up afterwards.

The 90 matches already loaded keep both columns at NULL, so there is no backfill.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel columns render as sqlmodel.sql.sqltypes.AutoString


# revision identifiers, used by Alembic.
revision: str = '3b7e1c4a92d5'
down_revision: Union[str, Sequence[str], None] = '80cb646c05dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'matches',
        sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    )
    op.add_column(
        'matches',
        sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=280), nullable=True),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('matches', 'comment')
    op.drop_column('matches', 'photo_url')
